In [51]:
%reload_ext autoreload
%autoreload 2

In [2]:
from sklearn.metrics import confusion_matrix

In [5]:
remote_path = 'data-platform/datasets/1/cv/mnist.zip'

print(os.path.basename(remote_path))
print(os.path.dirname(remote_path))

mnist.zip
data-platform/datasets/1/cv


In [10]:
os.path.join('/a', 'b')

bucket = 'data-platform'
rfile = 'data-platform/dataset/a/b.jsp'
rfile[len(bucket) + 1:]

'dataset/a/b.jsp'

In [3]:
confusion_matrix([1,2,1,1,2], [2,1,2,1,1])

array([[1, 2],
       [2, 0]])

In [4]:
import torch



In [21]:
a = torch.Tensor([1])
a

tensor([1.])

In [20]:
b = torch.IntTensor([1])
b

tensor([1], dtype=torch.int32)

In [24]:
a != b

tensor([False])

In [23]:
type(a)

torch.Tensor