In [51]:
%reload_ext autoreload
%autoreload 2

In [1]:
import os
import torch

In [3]:
a = torch.ones([1,2])
a

tensor([[1., 1.]])

In [9]:
(a,b)

(tensor([[1., 1.]]), tensor([[1., 1.]]))

In [10]:
b = torch.ones([1,2])

c = torch.stack((a,b), 0)
c

tensor([[[1., 1.]],

        [[1., 1.]]])

In [5]:
b = torch.ones([2,3])
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
d = torch.randint(0, 10, (4,6))

In [17]:
d.data

tensor([[7, 3, 8, 7, 3, 4],
        [5, 2, 4, 7, 0, 9],
        [7, 7, 5, 2, 8, 3],
        [7, 7, 2, 7, 6, 2]])

In [5]:
a = 'k12cv'

b = f'{a[3:]}'
b

'cv'