In [51]:
%reload_ext autoreload
%autoreload 2

In [2]:
from sklearn.metrics import confusion_matrix

In [5]:
remote_path = 'data-platform/datasets/1/cv/mnist.zip'

print(os.path.basename(remote_path))
print(os.path.dirname(remote_path))

mnist.zip
data-platform/datasets/1/cv


In [10]:
os.path.join('/a', 'b')

bucket = 'data-platform'
rfile = 'data-platform/dataset/a/b.jsp'
rfile[len(bucket) + 1:]

'dataset/a/b.jsp'

In [3]:
confusion_matrix([1,2,1,1,2], [2,1,2,1,1])

array([[1, 2],
       [2, 0]])

In [4]:
import torch



In [21]:
a = torch.Tensor([1])
a

tensor([1.])

In [20]:
b = torch.IntTensor([1])
b

tensor([1], dtype=torch.int32)

In [24]:
a != b

tensor([False])

In [23]:
type(a)

torch.Tensor

In [40]:
import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
_b('\n\x1fvulkan/protos/layers/conv.proto\"\xa1\x01\n\x0e\x63onv_parameter\x12\x13\n\x0bin_channels\x18\x01 \x01(\t\x12\x14\n\x0cout_channels\x18\x02 \x01(\t\x12\x13\n\x0bkernel_size\x18\x03 \x03(\t\x12\x0e\n\x06stride\x18\x04 \x03(\t\x12\x0f\n\x07padding\x18\x05 \x03(\t\x12\x10\n\x08\x64ilation\x18\x06 \x03(\t\x12\x0e\n\x06groups\x18\x07 \x01(\t\x12\x0c\n\x04\x62ias\x18\x08 \x01(\t\"\x97\x01\n\tConvLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1d\n\nlayer_mode\x18\x04 \x01(\x0e\x32\t.ConvMode\x12%\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x0f.conv_parameter\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*a\n\x08\x43onvMode\x12\n\n\x06\x43ONV1D\x10\x00\x12\n\n\x06\x43ONV2D\x10\x01\x12\n\n\x06\x43ONV3D\x10\x02\x12\x0f\n\x0bTRANSCONV1D\x10\x03\x12\x0f\n\x0bTRANSCONV2D\x10\x04\x12\x0f\n\x0bTRANSCONV3D\x10\x05')

b'\n\x1fvulkan/protos/layers/conv.proto"\xa1\x01\n\x0econv_parameter\x12\x13\n\x0bin_channels\x18\x01 \x01(\t\x12\x14\n\x0cout_channels\x18\x02 \x01(\t\x12\x13\n\x0bkernel_size\x18\x03 \x03(\t\x12\x0e\n\x06stride\x18\x04 \x03(\t\x12\x0f\n\x07padding\x18\x05 \x03(\t\x12\x10\n\x08dilation\x18\x06 \x03(\t\x12\x0e\n\x06groups\x18\x07 \x01(\t\x12\x0c\n\x04bias\x18\x08 \x01(\t"\x97\x01\n\tConvLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1d\n\nlayer_mode\x18\x04 \x01(\x0e2\t.ConvMode\x12%\n\x0clayer_params\x18\x05 \x01(\x0b2\x0f.conv_parameter\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*a\n\x08ConvMode\x12\n\n\x06CONV1D\x10\x00\x12\n\n\x06CONV2D\x10\x01\x12\n\n\x06CONV3D\x10\x02\x12\x0f\n\x0bTRANSCONV1D\x10\x03\x12\x0f\n\x0bTRANSCONV2D\x10\x04\x12\x0f\n\x0bTRANSCONV3D\x10\x05'

In [42]:
a=_b('\n\x1fvulkan/protos/layers/conv.proto\"\xa1\x01\n\x0e\x63onv_parameter\x12\x13\n\x0bin_channels\x18\x01 \x01(\t\x12\x14\n\x0cout_channels\x18\x02 \x01(\t\x12\x13\n\x0bkernel_size\x18\x03 \x03(\t\x12\x0e\n\x06stride\x18\x04 \x03(\t\x12\x0f\n\x07padding\x18\x05 \x03(\t\x12\x10\n\x08\x64ilation\x18\x06 \x03(\t\x12\x0e\n\x06groups\x18\x07 \x01(\t\x12\x0c\n\x04\x62ias\x18\x08 \x01(\t\"\x97\x01\n\tConvLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1d\n\nlayer_mode\x18\x04 \x01(\x0e\x32\t.ConvMode\x12%\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x0f.conv_parameter\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*a\n\x08\x43onvMode\x12\n\n\x06\x43ONV1D\x10\x00\x12\n\n\x06\x43ONV2D\x10\x01\x12\n\n\x06\x43ONV3D\x10\x02\x12\x0f\n\x0bTRANSCONV1D\x10\x03\x12\x0f\n\x0bTRANSCONV2D\x10\x04\x12\x0f\n\x0bTRANSCONV3D\x10\x05')

In [43]:
str(a)

'b\'\\n\\x1fvulkan/protos/layers/conv.proto"\\xa1\\x01\\n\\x0econv_parameter\\x12\\x13\\n\\x0bin_channels\\x18\\x01 \\x01(\\t\\x12\\x14\\n\\x0cout_channels\\x18\\x02 \\x01(\\t\\x12\\x13\\n\\x0bkernel_size\\x18\\x03 \\x03(\\t\\x12\\x0e\\n\\x06stride\\x18\\x04 \\x03(\\t\\x12\\x0f\\n\\x07padding\\x18\\x05 \\x03(\\t\\x12\\x10\\n\\x08dilation\\x18\\x06 \\x03(\\t\\x12\\x0e\\n\\x06groups\\x18\\x07 \\x01(\\t\\x12\\x0c\\n\\x04bias\\x18\\x08 \\x01(\\t"\\x97\\x01\\n\\tConvLayer\\x12\\x0c\\n\\x04name\\x18\\x01 \\x01(\\t\\x12\\x0e\\n\\x06inputs\\x18\\x02 \\x03(\\t\\x12\\x0f\\n\\x07outputs\\x18\\x03 \\x03(\\t\\x12\\x1d\\n\\nlayer_mode\\x18\\x04 \\x01(\\x0e2\\t.ConvMode\\x12%\\n\\x0clayer_params\\x18\\x05 \\x01(\\x0b2\\x0f.conv_parameter\\x12\\x15\\n\\rlayer_builder\\x18\\x06 \\x01(\\t*a\\n\\x08ConvMode\\x12\\n\\n\\x06CONV1D\\x10\\x00\\x12\\n\\n\\x06CONV2D\\x10\\x01\\x12\\n\\n\\x06CONV3D\\x10\\x02\\x12\\x0f\\n\\x0bTRANSCONV1D\\x10\\x03\\x12\\x0f\\n\\x0bTRANSCONV2D\\x10\\x04\\x12\\x0f\\n\\x0bTRANSCONV