In [87]:
%reload_ext watermark
%reload_ext autoreload
%autoreload 2
%watermark -v -p numpy,sklearn,pandas
%watermark -v -p cv2,PIL,matplotlib
%watermark -v -p torch,torchvision,torchaudio,pytorch_lightning
%matplotlib inline
%config InlineBackend.figure_format='retina'
%config IPCompleter.use_jedi = False


from IPython.display import display, HTML
display(HTML('<style>.container { width:%d%% !important; }</style>' % 90))

CPython 3.6.9
IPython 7.16.1

numpy 1.19.4
sklearn 0.24.0
pandas 1.1.5
CPython 3.6.9
IPython 7.16.1

cv2 4.5.1
PIL 6.2.2
matplotlib 3.3.3
CPython 3.6.9
IPython 7.16.1

torch 1.8.0.dev20210103+cu101
torchvision 0.9.0.dev20210103+cu101
torchaudio not installed
pytorch_lightning 1.2.0


In [88]:
import torch
import numpy as py
from torch import nn

from torch.nn import functional as F

In [89]:
# torch.Size([20, 512, 64, 7, 7])


In [90]:
x_1 = torch.randn(1, 8, 3, 7, 7)
print(x_1[0][0][0], x_1.shape)

tensor([[-7.0698e-01,  1.4630e+00,  2.2404e-01,  1.2778e+00,  9.3863e-01,
         -1.0775e+00, -9.1196e-02],
        [ 1.2175e+00,  2.3973e+00,  6.3833e-01,  2.0186e+00,  4.7256e-01,
          1.0317e+00, -3.0660e-01],
        [ 1.1798e-01, -4.8614e-01, -4.7417e-01, -1.0714e-01,  7.7726e-01,
          2.6627e-01, -6.9396e-01],
        [ 9.7417e-01, -1.9320e+00, -7.7859e-01,  1.7791e-01,  8.5951e-01,
          4.2497e-01,  1.2543e+00],
        [-4.3450e-01,  6.9026e-01,  1.2539e+00,  1.6477e-01, -1.8509e-03,
         -4.4215e-01, -1.4844e+00],
        [-7.3668e-01, -9.7952e-01,  4.8097e-01, -1.0532e+00, -2.7018e-01,
         -1.0188e+00,  7.9379e-01],
        [ 1.5657e+00,  1.0586e+00, -2.6934e-02, -1.3509e+00,  2.7975e-01,
          3.5562e-02,  4.3079e-01]]) torch.Size([1, 8, 3, 7, 7])


In [91]:
x, y = torch.max(x_1, dim=3)
# print(x[0][0][0], x.shape)
x, y = torch.max(x, dim=3)
print(x[0][0], x.shape)

tensor([2.3973, 2.0273, 1.7461]) torch.Size([1, 8, 3])


In [92]:
m = nn.AdaptiveMaxPool3d((3,1,1))
output = m(x_1)
print(output[0][0], output.shape)

tensor([[[2.3973]],

        [[2.0273]],

        [[1.7461]]]) torch.Size([1, 8, 3, 1, 1])


In [98]:
output = F.adaptive_max_pool3d(x_1, (3, 1, 1)).reshape(1, 8, 3)
print(output[0][0], output.shape)

tensor([2.3973, 2.0273, 1.7461]) torch.Size([1, 8, 3])


torch.Size([8, 3])

In [103]:
import random
random.random()

0.2784630599733191

In [1]:
fff = 10

In [2]:
fff

10

```json

{
  'a'
}

```