In [13]:
%reload_ext watermark
%reload_ext autoreload
%autoreload 2
%watermark -v -p numpy,sklearn,pandas
%watermark -v -p cv2,PIL,matplotlib
%watermark -v -p torch,torchvision,torchaudio
%matplotlib inline
%config InlineBackend.figure_format='retina'
%config IPCompleter.use_jedi = False

from IPython.display import display, Markdown, HTML, Javascript
display(HTML('<style>.container { width:%d%% !important; }</style>' % 80))

import sys, os, io, time, random, math
import json, base64, requests
import os.path as osp

def _IMPORT_(x):
    try:
        segs = x.split(' ')
        g = globals()
        if 'github.com' in segs[1]:
            uri = segs[1].replace('github.com', 'raw.githubusercontent.com')
            mod = uri.split('/')
            uri = 'https://' + '/'.join(mod[:-1]) + '/main/' + mod[-1] + '.py'
            x = requests.get(uri).text
        elif 'gitee.com' in segs[1]:
            mod = segs[1].split('/')
            uri = 'https://' + '/'.join(mod[:-1]) + '/raw/main/' + mod[-1] + '.py'
            x = requests.get(uri).text
        elif segs[1][0] == '/':
            with open(segs[1] + '.py') as fr:
                x = fr.read()
        exec(x, g)
    except:
        pass
    

def print_progress_bar(x):
    print('\r', end='')
    print('Progress: {}%:'.format(x), '%s%s' % ('▋'*(x//2), '.'*((100-x)//2)), end='')
    sys.stdout.flush()

def img2b64(x):
    if isinstance(x, bytes):
        return base64.b64encode(x).decode()
    elif isinstance(x, str):
        with open(x, 'rb') as fr:
            return base64.b64encode(fr.read()).decode()
    raise

###
### Common ###
###

_IMPORT_('import numpy as np')
_IMPORT_('import pandas as pd')
_IMPORT_('from tqdm.notebook import tqdm')


CPython 3.6.9
IPython 7.16.1

numpy 1.19.4
sklearn 0.24.0
pandas 1.1.5
CPython 3.6.9
IPython 7.16.1

cv2 4.5.1
PIL 6.2.2
matplotlib 3.3.3
CPython 3.6.9
IPython 7.16.1

torch 1.8.0.dev20210103+cu101
torchvision 0.9.0.dev20210103+cu101
torchaudio not installed


In [74]:
a = { 'a': {'c': [12,2]}, 'b': 20}

In [79]:
a = [10, (10, 20), (20, 30)]
a[1]

(10, 20)

In [69]:
a

{'b': 20}

In [59]:
int(np.clip(10, 11, 20))

11

In [60]:
x = 

In [66]:
min(max(0, 31), 30)

30

In [35]:
b = a[a[:, 1].argsort()]
b

array([[0, 1, 2],
       [1, 2, 3],
       [5, 4, 3]])

In [51]:
c = np.array([[0,1,2],[1,2,3], [5,4,3]])
c

array([[0, 1, 2],
       [1, 2, 3],
       [5, 4, 3]])

In [52]:
for x in reversed(c):
    print(x)

[5 4 3]
[1 2 3]
[0 1 2]


In [46]:
for x in b:
    print(x)

[0 1 2]
[1 2 3]
[5 4 3]


In [41]:
for x in reversed(a[a[:, 1].argsort()]):
    print(x)

[5 4 3]
[1 2 3]
[0 1 2]


In [43]:
for x in a[a[:, 1].argsort()]:
    print(x)

[0 1 2]
[1 2 3]
[5 4 3]


In [1]:
from ipywidgets import RadioButtons, Text, Select, Dropdown, jslink, interactive, interact
from ipywidgets.widgets.widget import Widget, register, widget_serialization
from ipywidgets.widgets.widget_core import CoreWidget
from IPython.display import  display
import ipywidgets as widgets
# from ipywidgets.trait_types import CByteMemoryView         


from traitlets import CBytes, Unicode, Tuple, Instance, TraitError

Dropdown.value.tag(sync=True)

selection = Dropdown(options=[
    ('1', 'https://raceai.s3.didiyunapi.com/data/media/videos/repnet/20210720143047.mp4'),
    ('2', 'https://raceai.s3.didiyunapi.com/data/media/videos/repnet/20210720143047.mp4'),
    ('3', 'https://raceai.s3.didiyunapi.com/data/media/videos/repnet/20210720143047.mp4')])

class BytesText(Text):
    bvalue = CBytes(help="Bytes value").tag(sync=True)       

text = BytesText(value='a')
# l = jslink((text, 'value'), (selection, 'value'))
def test(a):
    print(a)
    
def observe_test(wdg):
    print(wdg)
    wdg['owner'].bvalue = wdg['new'].encode('utf-8')
    
o = text.observe(observe_test, 'value')
    
# interact(test, a=text);

video = widgets.Video(format='url')

l = jslink((text, 'bvalue'), (video, 'value'))

# display(selection, video)
display(text, video)

BytesText(value='a')

Video(value=b'', format='url')

In [170]:
data = {'pigeon': {'msgkey': 'nb.zmq.repnet_tf.gamma102.det', 'user': 'private', 'uuid': 'repnet_tf'}, 'task': 'zmq.yolov5.ladder.l.inference', 'errno': 0, 'result': [{'image_path': '0.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.948', 'xyxy': [223, 55, 368, 105]}]}, {'image_path': '150.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.937', 'xyxy': [223, 59, 365, 107]}]}, {'image_path': '300.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.909', 'xyxy': [218, 64, 360, 113]}]}, {'image_path': '450.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.901', 'xyxy': [219, 62, 364, 116]}, {'label': 0, 'conf': '0.937', 'xyxy': [219, 58, 369, 109]}]}, {'image_path': '600.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.915', 'xyxy': [222, 62, 374, 106]}]}, {'image_path': '750.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.927', 'xyxy': [219, 58, 368, 108]}]}, {'image_path': '900.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.945', 'xyxy': [278, 42, 378, 91]}, {'label': 0, 'conf': '0.956', 'xyxy': [0, 6, 51, 35]}]}, {'image_path': '1050.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.964', 'xyxy': [220, 58, 371, 106]}]}, {'image_path': '1200.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.939', 'xyxy': [218, 56, 372, 108]}]}, {'image_path': '1350.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.908', 'xyxy': [224, 55, 361, 115]}, {'label': 0, 'conf': '0.951', 'xyxy': [220, 50, 370, 109]}, {'label': 0, 'conf': '0.979', 'xyxy': [2, 6, 51, 37]}]}, {'image_path': '1500.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.938', 'xyxy': [222, 51, 360, 112]}]}, {'image_path': '1650.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.947', 'xyxy': [221, 54, 368, 111]}]}, {'image_path': '1800.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.964', 'xyxy': [221, 56, 370, 108]}]}, {'image_path': '1950.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.940', 'xyxy': [220, 50, 377, 110]}]}, {'image_path': '2100.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.947', 'xyxy': [222, 57, 358, 109]}]}, {'image_path': '2250.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.903', 'xyxy': [1, 4, 51, 36]}, {'label': 0, 'conf': '0.923', 'xyxy': [222, 57, 367, 102]}]}, {'image_path': '2400.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.942', 'xyxy': [218, 49, 372, 110]}]}, {'image_path': '2550.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.959', 'xyxy': [223, 62, 370, 101]}]}, {'image_path': '2700.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.956', 'xyxy': [224, 56, 370, 101]}]}, {'image_path': '2850.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.904', 'xyxy': [220, 52, 364, 101]}, {'label': 0, 'conf': '0.910', 'xyxy': [222, 57, 354, 103]}, {'label': 0, 'conf': '0.965', 'xyxy': [0, 5, 50, 36]}]}, {'image_path': '3000.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.904', 'xyxy': [0, 4, 51, 35]}, {'label': 0, 'conf': '0.947', 'xyxy': [223, 55, 370, 99]}]}, {'image_path': '3150.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '3300.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.910', 'xyxy': [1, 8, 51, 36]}]}, {'image_path': '3450.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '3600.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '3750.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '3900.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '4050.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.926', 'xyxy': [224, 50, 366, 106]}]}, {'image_path': '4200.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.949', 'xyxy': [223, 55, 367, 99]}]}, {'image_path': '4350.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.922', 'xyxy': [220, 45, 371, 105]}]}, {'image_path': '4500.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.957', 'xyxy': [220, 59, 370, 106]}]}, {'image_path': '4650.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.955', 'xyxy': [222, 61, 357, 111]}]}, {'image_path': '4800.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.968', 'xyxy': [224, 59, 364, 103]}]}, {'image_path': '4950.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.953', 'xyxy': [1, 8, 52, 37]}]}, {'image_path': '5100.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.943', 'xyxy': [1, 5, 51, 35]}, {'label': 0, 'conf': '0.960', 'xyxy': [222, 59, 374, 104]}]}, {'image_path': '5250.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.918', 'xyxy': [1, 107, 51, 136]}, {'label': 0, 'conf': '0.930', 'xyxy': [1, 4, 52, 34]}, {'label': 0, 'conf': '0.964', 'xyxy': [222, 53, 370, 108]}]}, {'image_path': '5400.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.968', 'xyxy': [223, 52, 372, 107]}]}, {'image_path': '5550.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.924', 'xyxy': [220, 55, 365, 104]}]}, {'image_path': '5700.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.901', 'xyxy': [222, 57, 364, 104]}]}, {'image_path': '5850.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.955', 'xyxy': [222, 51, 370, 106]}]}, {'image_path': '6000.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.966', 'xyxy': [221, 61, 374, 103]}]}, {'image_path': '6150.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.958', 'xyxy': [223, 55, 371, 106]}]}, {'image_path': '6300.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.958', 'xyxy': [219, 59, 374, 109]}]}, {'image_path': '6450.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.900', 'xyxy': [212, 62, 386, 108]}, {'label': 0, 'conf': '0.966', 'xyxy': [0, 5, 52, 35]}, {'label': 0, 'conf': '0.967', 'xyxy': [222, 64, 367, 106]}]}, {'image_path': '6600.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.945', 'xyxy': [226, 55, 358, 105]}]}, {'image_path': '6750.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.954', 'xyxy': [225, 56, 371, 102]}, {'label': 0, 'conf': '0.990', 'xyxy': [0, 6, 52, 34]}]}, {'image_path': '6900.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '7050.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '7200.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.957', 'xyxy': [1, 1, 52, 40]}, {'label': 0, 'conf': '0.970', 'xyxy': [225, 60, 371, 107]}]}, {'image_path': '7350.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.957', 'xyxy': [226, 54, 361, 106]}]}, {'image_path': '7500.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.946', 'xyxy': [222, 59, 358, 107]}, {'label': 0, 'conf': '0.987', 'xyxy': [0, 2, 52, 37]}]}, {'image_path': '7650.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.910', 'xyxy': [1, 3, 52, 34]}, {'label': 0, 'conf': '0.964', 'xyxy': [220, 52, 370, 109]}]}, {'image_path': '7800.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.930', 'xyxy': [0, 13, 51, 40]}, {'label': 0, 'conf': '0.964', 'xyxy': [222, 53, 365, 108]}, {'label': 0, 'conf': '0.985', 'xyxy': [0, 6, 53, 39]}]}, {'image_path': '7950.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.956', 'xyxy': [222, 57, 363, 107]}, {'label': 0, 'conf': '0.966', 'xyxy': [0, 3, 52, 34]}]}, {'image_path': '8100.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.933', 'xyxy': [0, 4, 51, 38]}, {'label': 0, 'conf': '0.966', 'xyxy': [221, 53, 369, 108]}]}, {'image_path': '8250.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.927', 'xyxy': [225, 57, 357, 106]}, {'label': 0, 'conf': '0.940', 'xyxy': [221, 47, 365, 100]}, {'label': 0, 'conf': '0.972', 'xyxy': [0, 3, 51, 36]}]}, {'image_path': '8400.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.951', 'xyxy': [219, 48, 373, 109]}]}, {'image_path': '8550.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.958', 'xyxy': [222, 54, 371, 108]}, {'label': 0, 'conf': '0.968', 'xyxy': [0, 3, 50, 38]}]}, {'image_path': '8700.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.928', 'xyxy': [1, 8, 51, 37]}, {'label': 0, 'conf': '0.964', 'xyxy': [222, 58, 362, 107]}]}, {'image_path': '8850.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.924', 'xyxy': [221, 50, 365, 105]}, {'label': 0, 'conf': '0.943', 'xyxy': [227, 57, 358, 105]}]}, {'image_path': '9000.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.956', 'xyxy': [0, 3, 51, 34]}, {'label': 0, 'conf': '0.962', 'xyxy': [220, 54, 369, 107]}]}, {'image_path': '9150.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.918', 'xyxy': [222, 59, 371, 103]}, {'label': 0, 'conf': '0.989', 'xyxy': [0, 5, 51, 37]}]}, {'image_path': '9300.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.962', 'xyxy': [224, 54, 366, 103]}]}, {'image_path': '9450.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.940', 'xyxy': [222, 49, 366, 106]}, {'label': 0, 'conf': '0.944', 'xyxy': [222, 53, 357, 111]}]}, {'image_path': '9600.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.955', 'xyxy': [220, 54, 366, 106]}, {'label': 0, 'conf': '0.966', 'xyxy': [0, 5, 52, 32]}]}, {'image_path': '9750.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.949', 'xyxy': [222, 56, 370, 107]}, {'label': 0, 'conf': '0.966', 'xyxy': [0, 3, 51, 36]}]}, {'image_path': '9900.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.952', 'xyxy': [221, 58, 370, 107]}]}, {'image_path': '10050.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.943', 'xyxy': [220, 57, 368, 107]}]}, {'image_path': '10200.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.951', 'xyxy': [223, 57, 364, 106]}]}, {'image_path': '10350.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.962', 'xyxy': [220, 56, 368, 107]}]}, {'image_path': '10500.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '10650.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.917', 'xyxy': [222, 54, 367, 106]}, {'label': 0, 'conf': '0.920', 'xyxy': [1, 6, 51, 34]}, {'label': 0, 'conf': '0.942', 'xyxy': [223, 60, 361, 109]}]}, {'image_path': '10800.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.958', 'xyxy': [226, 62, 362, 104]}]}, {'image_path': '10950.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.948', 'xyxy': [223, 56, 372, 106]}]}, {'image_path': '11100.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.908', 'xyxy': [0, 13, 51, 38]}, {'label': 0, 'conf': '0.967', 'xyxy': [220, 62, 365, 106]}, {'label': 0, 'conf': '0.992', 'xyxy': [0, 7, 52, 37]}]}, {'image_path': '11250.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.962', 'xyxy': [224, 61, 362, 104]}]}, {'image_path': '11400.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.914', 'xyxy': [424, 39, 462, 85]}, {'label': 0, 'conf': '0.948', 'xyxy': [220, 57, 376, 107]}, {'label': 0, 'conf': '0.972', 'xyxy': [0, 6, 51, 36]}]}, {'image_path': '11550.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.909', 'xyxy': [0, 107, 51, 136]}, {'label': 0, 'conf': '0.911', 'xyxy': [221, 53, 372, 104]}, {'label': 0, 'conf': '0.957', 'xyxy': [0, 6, 51, 34]}]}, {'image_path': '11700.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.937', 'xyxy': [0, 5, 52, 33]}, {'label': 0, 'conf': '0.962', 'xyxy': [220, 59, 373, 105]}]}, {'image_path': '11850.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.958', 'xyxy': [226, 61, 371, 106]}]}, {'image_path': '12000.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.947', 'xyxy': [222, 52, 373, 104]}]}, {'image_path': '12150.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '12300.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.969', 'xyxy': [221, 60, 379, 109]}]}, {'image_path': '12450.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.908', 'xyxy': [223, 60, 356, 107]}, {'label': 0, 'conf': '0.971', 'xyxy': [229, 62, 363, 102]}, {'label': 0, 'conf': '0.983', 'xyxy': [0, 4, 52, 38]}]}, {'image_path': '12600.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.907', 'xyxy': [275, 44, 379, 97]}, {'label': 0, 'conf': '0.959', 'xyxy': [220, 58, 364, 105]}]}, {'image_path': '12750.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.904', 'xyxy': [222, 57, 364, 103]}, {'label': 0, 'conf': '0.934', 'xyxy': [221, 63, 359, 106]}]}, {'image_path': '12900.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.914', 'xyxy': [221, 64, 351, 108]}]}, {'image_path': '13050.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '13200.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '13350.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.974', 'xyxy': [0, 2, 52, 37]}]}, {'image_path': '13500.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.941', 'xyxy': [1, 6, 52, 35]}]}, {'image_path': '13650.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.980', 'xyxy': [0, 1, 52, 40]}]}, {'image_path': '13800.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': []}, {'image_path': '13950.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.929', 'xyxy': [0, 4, 52, 37]}]}, {'image_path': '14100.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.909', 'xyxy': [1, 4, 54, 32]}, {'label': 0, 'conf': '0.955', 'xyxy': [219, 57, 375, 108]}]}, {'image_path': '14250.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.902', 'xyxy': [1, 3, 50, 35]}]}, {'image_path': '14400.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.968', 'xyxy': [220, 55, 373, 106]}, {'label': 0, 'conf': '0.971', 'xyxy': [0, 3, 51, 37]}]}, {'image_path': '14550.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.957', 'xyxy': [222, 55, 374, 108]}, {'label': 0, 'conf': '0.975', 'xyxy': [0, 5, 52, 35]}]}, {'image_path': '14700.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.963', 'xyxy': [223, 59, 359, 107]}]}, {'image_path': '14850.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.938', 'xyxy': [223, 59, 358, 108]}]}, {'image_path': '15000.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.969', 'xyxy': [221, 55, 373, 108]}]}, {'image_path': '15150.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.904', 'xyxy': [1, 5, 51, 33]}, {'label': 0, 'conf': '0.926', 'xyxy': [221, 56, 376, 105]}]}, {'image_path': '15300.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.957', 'xyxy': [223, 61, 360, 109]}, {'label': 0, 'conf': '0.963', 'xyxy': [0, 3, 51, 37]}]}, {'image_path': '15450.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.913', 'xyxy': [223, 56, 363, 109]}, {'label': 0, 'conf': '0.929', 'xyxy': [221, 46, 368, 105]}, {'label': 0, 'conf': '0.956', 'xyxy': [0, 5, 51, 33]}]}, {'image_path': '15600.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.950', 'xyxy': [223, 58, 365, 108]}, {'label': 0, 'conf': '0.987', 'xyxy': [0, 6, 54, 37]}]}, {'image_path': '15750.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.928', 'xyxy': [224, 61, 371, 104]}, {'label': 0, 'conf': '0.969', 'xyxy': [0, 5, 51, 35]}]}, {'image_path': '15900.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.938', 'xyxy': [222, 57, 364, 107]}, {'label': 0, 'conf': '0.970', 'xyxy': [0, 3, 51, 34]}]}, {'image_path': '16050.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.933', 'xyxy': [221, 56, 369, 108]}, {'label': 0, 'conf': '0.936', 'xyxy': [1, 4, 50, 34]}]}, {'image_path': '16200.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.904', 'xyxy': [0, 4, 50, 34]}, {'label': 0, 'conf': '0.940', 'xyxy': [221, 56, 370, 107]}]}, {'image_path': '16350.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.954', 'xyxy': [221, 58, 374, 107]}]}, {'image_path': '16500.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.942', 'xyxy': [220, 50, 373, 108]}]}, {'image_path': '16650.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.905', 'xyxy': [1, 106, 52, 134]}, {'label': 0, 'conf': '0.932', 'xyxy': [223, 55, 368, 105]}, {'label': 0, 'conf': '0.949', 'xyxy': [224, 61, 360, 108]}]}, {'image_path': '16800.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.917', 'xyxy': [222, 56, 370, 105]}, {'label': 0, 'conf': '0.975', 'xyxy': [0, 3, 51, 36]}]}, {'image_path': '16950.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.945', 'xyxy': [223, 59, 372, 104]}, {'label': 0, 'conf': '0.982', 'xyxy': [0, 4, 51, 37]}]}, {'image_path': '17100.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.951', 'xyxy': [221, 61, 371, 109]}]}, {'image_path': '17250.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.957', 'xyxy': [225, 56, 360, 105]}, {'label': 0, 'conf': '0.966', 'xyxy': [0, 5, 52, 36]}]}, {'image_path': '17400.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.933', 'xyxy': [223, 58, 368, 103]}]}, {'image_path': '17550.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.931', 'xyxy': [1, 5, 50, 33]}, {'label': 0, 'conf': '0.939', 'xyxy': [221, 59, 369, 107]}]}, {'image_path': '17700.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.920', 'xyxy': [0, 5, 50, 35]}, {'label': 0, 'conf': '0.958', 'xyxy': [222, 58, 375, 106]}]}, {'image_path': '17850.jpg', 'image_width': 640, 'image_height': 352, 'predict_box': [{'label': 0, 'conf': '0.952', 'xyxy': [221, 58, 373, 107]}, {'label': 0, 'conf': '0.978', 'xyxy': [0, 6, 51, 36]}]}], 'running_time': 5.151}

In [171]:
from collections import Counter
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist

centers = []
detect_box = {}
for result in data['result']:
    frame_idx = int(result['image_path'].split('.')[0])
    imagew = result['image_width']
    imageh = result['image_height']
    box = result['predict_box']
    if len(box) > 0:
        detect_box[frame_idx] = box[-1]
        xyxy = box[-1]['xyxy'] # last is the max confidence score
        centers.append((int(0.5 * (xyxy[0] + xyxy[2])), int(0.5 * (xyxy[1] + xyxy[3]))))
centers = np.array(centers)

In [172]:
half = int(0.5 * len(centers))
half

54

In [173]:
c1 = centers[:half]
c2 = centers[half:]
len(c1) + len(c2)

108

In [181]:
model = KMeans(n_clusters=3)
clusters = model.fit_predict(centers)
cluster_centers = model.cluster_centers_

clusters2 = model.fit_predict(c2)
cluster_centers2 = model.cluster_centers_

clusters1 = model.fit_predict(c1)
cluster_centers1 = model.cluster_centers_

In [201]:
cluster_centers1, cluster_centers2, cluster_centers

(array([[296.04545455,  79.5       ],
        [ 25.63636364,  20.27272727],
        [292.95238095,  82.33333333]]),
 array([[290.8       ,  83.        ],
        [ 25.45833333,  19.875     ],
        [296.2       ,  81.45      ]]),
 array([[296.06521739,  80.56521739],
        [ 25.51428571,  20.        ],
        [291.77777778,  82.62962963]]))

In [149]:
clusters

array([2, 0, 0, 0, 2, 0, 1, 2, 2, 1, 0, 0, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 1, 0, 0, 2, 1, 2, 0, 1, 1, 2, 0, 0, 2, 0, 0, 2,
       1, 0, 1, 1, 2, 2, 2, 2, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0,
       2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1],
      dtype=int32)

In [179]:
clusters1, clusters2

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))

In [204]:
cluster_centers1, cluster_centers2

(array([[296.04545455,  79.5       ],
        [ 25.63636364,  20.27272727],
        [292.95238095,  82.33333333]]),
 array([[290.8       ,  83.        ],
        [ 25.45833333,  19.875     ],
        [296.2       ,  81.45      ]]))

In [205]:
cluster_centers.mean(axis=0), cluster_centers1.mean(axis=0), cluster_centers2.mean(axis=0)

(array([204.45242696,  61.06494901]),
 array([204.87806638,  60.7020202 ]),
 array([204.15277778,  61.44166667]))

In [185]:
a, b = cluster_centers1.mean(axis=0), cluster_centers2.mean(axis=0)

In [196]:
c = a - b
c

array([ 0.7252886 , -0.73964646])

In [197]:
c[0] * c[0]

0.5260435537086277

In [191]:
np.square(a - b)

array([0.52604355, 0.54707689])

(array([41975.02208282,  3684.73525661]),
 array([41678.35667438,  3775.07840278]))

In [206]:
op1=np.sqrt(np.sum(np.square(a-b)))
op2=np.linalg.norm(a-b)

In [189]:
op1, op2

(1.0359152698810214, 1.0359152698810214)

In [186]:
np.disp

array([0.52604355, 0.54707689])

In [198]:
Counter(clusters).most_common()[0][0]

0

In [133]:
data = model.cluster_centers_
data

array([[ 25.51428571,  20.        ],
       [293.77419355,  81.41935484],
       [296.05882353,  78.41176471],
       [297.26666667,  82.46666667],
       [289.8       ,  84.3       ]])

In [142]:
dist = cdist(data, data, metric='euclidean')
print(dist)

[[  0.         275.20122692 276.77839727 278.8394538  271.99527344]
 [275.20122692   0.           3.77692104   3.64612542   4.90839392]
 [276.77839727   3.77692104   0.           4.23097092   8.59326404]
 [278.8394538    3.64612542   4.23097092   0.           7.68844732]
 [271.99527344   4.90839392   8.59326404   7.68844732   0.        ]]


In [147]:
dist > 15

array([[False,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [145]:
print(dist[dist > 15])

[275.20122692 276.77839727 278.8394538  271.99527344 275.20122692
 276.77839727 278.8394538  271.99527344]


In [207]:
from PIL import Image

In [211]:
img = Image.open('./assets/add_layer.png')

In [212]:
type(img)

PIL.PngImagePlugin.PngImageFile