In [1]:
import numpy as np

## 多维数组降位一维

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

### 1. ravel: 解开, 散开, 返回的是view(C:行序时)

In [3]:
y1_1 = np.ravel(x) # C: 行序
y1_1

array([1, 2, 3, 4])

In [4]:
y1_1[0] *= 10
x

array([[10,  2],
       [ 3,  4]])

In [5]:
y1_2 = np.ravel(x, 'F') # F: 列序, 对其修改不影响原数据x ??
y1_2

array([10,  3,  2,  4])

In [6]:
y1_2[2] *= 10
x

array([[10,  2],
       [ 3,  4]])

### 2. flatten: 变平, 返回的是copy

In [7]:
y2_1 = x.flatten()
y2_1

array([10,  2,  3,  4])

In [8]:
y2_1[0] *= 10
x, y2_1

(array([[10,  2],
        [ 3,  4]]),
 array([100,   2,   3,   4]))

In [9]:
y2_2 = x.flatten('F')
y2_2

array([10,  3,  2,  4])

### 3. reshape: 拉平, 返回的是veiw(order:C)

In [10]:
x

array([[10,  2],
       [ 3,  4]])

In [11]:
y3_1 = x.reshape(-1)
y3_1

array([10,  2,  3,  4])

In [12]:
y2_1[1] *= 10
x

array([[10, 20],
       [ 3,  4]])

In [13]:
y3_2 = x.reshape(-1, order='F')
y3_2

array([10,  3, 20,  4])

In [14]:
y3_2[2] *= 10
x

array([[10, 20],
       [ 3,  4]])

### 4. sequeeze: 挤压 只对维度1降维

In [15]:
np.squeeze(x) # 无效

array([[10, 20],
       [ 3,  4]])

In [16]:
np.squeeze([[1],[2],[3]])

array([1, 2, 3])

----------------

## meshgrid

In [36]:
xx, yy = np.meshgrid(np.arange(0, 3, 1), np.arange(0, 3, 1))

In [37]:
xx.shape, yy.shape

((3, 3), (3, 3))

In [38]:
xx, yy

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]))

In [39]:
zz = np.c_[xx.ravel(), yy.ravel()]
zz.shape, zz

((9, 2),
 array([[0, 0],
        [1, 0],
        [2, 0],
        [0, 1],
        [1, 1],
        [2, 1],
        [0, 2],
        [1, 2],
        [2, 2]]))

In [41]:
zz[:, 0]

array([0, 1, 2, 0, 1, 2, 0, 1, 2])