# <div align="center"> 数学运算 </div>

In [1]:
import numpy as np

## np.multiply

### array multiply

In [4]:
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(0, 4).reshape(2, 2)
C = np.multiply(A, B)
A, B, C

(array([[1, 2],
        [3, 4]]),
 array([[0, 1],
        [2, 3]]),
 array([[ 0,  2],
        [ 6, 12]]))

### matrix nultiply

In [5]:
D = np.multiply(np.mat(A), np.mat(B))
D

matrix([[ 0,  2],
        [ 6, 12]])