In [1]:
import numpy as np

In [3]:
a = np.arange(23)

In [10]:
a = [2,4,5,1,1,1,1,1,1,1]
sorted(a, reverse=True)[:2]

[5, 4]

## split ...

In [14]:
data = np.arange(24).reshape(2, 3, 4)
data

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
data[:, :, :3]

array([[[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]],

       [[12, 13, 14],
        [16, 17, 18],
        [20, 21, 22]]])

In [16]:
data[..., :1]

array([[[ 0],
        [ 4],
        [ 8]],

       [[12],
        [16],
        [20]]])

## dot

In [18]:
np.dot([1,2,3], [0.5, 0.5, 0.5])

3.0

In [17]:
np.dot(data[..., :3], [0.5, 0.5, 0.5]) # 减少一个维度

array([[ 1.5,  7.5, 13.5],
       [19.5, 25.5, 31.5]])