# <div align="center"> Loss Functions </div>

In [1]:
%reload_ext watermark
%reload_ext autoreload
%autoreload 2
%watermark -v -p numpy,sklearn,pandas
%watermark -v -p cv2,PIL,matplotlib
%watermark -v -p torch,torchvision,torchaudio,pytorch_lightning
%matplotlib inline
%config InlineBackend.figure_format='retina'
%config IPCompleter.use_jedi = False

from IPython.display import display, HTML, Javascript
display(HTML('<style>.container { width:%d%% !important; }</style>' % 90))

def _IMPORT_(x):
    try:
        exec(x, globals())
    except:
        pass


CPython 3.6.9
IPython 7.16.1

numpy 1.18.5
sklearn 0.24.0
pandas 1.1.5
CPython 3.6.9
IPython 7.16.1

cv2 4.5.1
PIL 6.2.2
matplotlib 3.3.3
CPython 3.6.9
IPython 7.16.1

torch 1.8.0.dev20210103+cu101
torchvision 0.9.0.dev20210103+cu101
torchaudio not installed
pytorch_lightning 1.2.0


In [2]:
###
### Torch ###
###

_IMPORT_('import torch')
_IMPORT_('import torch.nn as nn')
_IMPORT_('import torch.nn.functional as F')
_IMPORT_('import torch.optim as O')
_IMPORT_('from torchvision import models as M')
_IMPORT_('from torchvision import transforms as T')
_IMPORT_('from torch.utils.data import Dataset, DataLoader')


## NLLLoss vs CrossEntropyLoss

In [3]:
X = torch.randn(2, 4)
y = torch.arange(0, 2)
X, y, X.shape, y.shape

(tensor([[-1.0619, -0.1077, -0.6097, -1.1655],
         [ 1.5475, -0.6481,  1.1606, -0.7103]]),
 tensor([0, 1]),
 torch.Size([2, 4]),
 torch.Size([2]))

### softmax range:(0, 1)

In [4]:
soft_output = F.softmax(X, dim=1)  # nn.Softmax(dim=1)
soft_output, soft_output.shape

(tensor([[0.1647, 0.4278, 0.2589, 0.1485],
         [0.5277, 0.0587, 0.3584, 0.0552]]),
 torch.Size([2, 4]))

### log_softmax range:(-inf, 0)

In [5]:
log_output = F.log_softmax(X, dim=1)  # nn.LogSoftmax(dim=1)
log_output, log_output.shape, torch.log(soft_output)

(tensor([[-1.8034, -0.8491, -1.3511, -1.9070],
         [-0.6393, -2.8349, -1.0261, -2.8970]]),
 torch.Size([2, 4]),
 tensor([[-1.8034, -0.8491, -1.3511, -1.9070],
         [-0.6393, -2.8349, -1.0261, -2.8970]]))

### nllloss

In [6]:
nlloss_output = F.nll_loss(log_output, y)  # nn.NLLLoss()
nlloss_output

tensor(2.3191)

### cross_entropy = log_softmax +  nllloss

In [7]:
ce_output = F.cross_entropy(X, y)
ce_output

tensor(2.3191)