In [1]:
import torch

In [2]:
x = torch.arange(1, 25)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

In [3]:
# TODO x.storage(): 为什么每次都在变动
id(x), id(x.storage()), x.data_ptr(), x.is_contiguous(), x.shape, x.size(), x.numel()

(140451234973232,
 140453303070664,
 68811648,
 True,
 torch.Size([24]),
 torch.Size([24]),
 24)

# view (contiguous)

In [4]:
view_0 = x.view(2, 3, 4)
view_0, view_0.shape, view_0.numel()

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]),
 torch.Size([2, 3, 4]),
 24)

In [5]:
id(view_0), id(view_0.storage()), view_0.data_ptr(), view_0.is_contiguous()

(140451234914240, 140453303267784, 68811648, True)

In [6]:
view_0[0][0][0] = 100
x, view_0

(tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24]),
 tensor([[[100,   2,   3,   4],
          [  5,   6,   7,   8],
          [  9,  10,  11,  12]],
 
         [[ 13,  14,  15,  16],
          [ 17,  18,  19,  20],
          [ 21,  22,  23,  24]]]))

In [7]:
view_1 = view_0.view(view_0.numel())
view_2 = view_0.view(-1) # equal view_1
view_1, view_1.data_ptr(), view_1.is_contiguous(), \
'-----------------------------------------------', \
view_2, view_2.data_ptr(), view_2.is_contiguous()

(tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24]),
 68811648,
 True,
 '-----------------------------------------------',
 tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24]),
 68811648,
 True)

In [8]:
view_3 = x.view(4, 6)
view_4 = view_3.t()

view_3, view_3.shape, view_3.is_contiguous(), \
'------------------------------------------', \
view_4, view_4.shape, view_4.is_contiguous()

(tensor([[100,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12],
         [ 13,  14,  15,  16,  17,  18],
         [ 19,  20,  21,  22,  23,  24]]),
 torch.Size([4, 6]),
 True,
 '------------------------------------------',
 tensor([[100,   7,  13,  19],
         [  2,   8,  14,  20],
         [  3,   9,  15,  21],
         [  4,  10,  16,  22],
         [  5,  11,  17,  23],
         [  6,  12,  18,  24]]),
 torch.Size([6, 4]),
 False)

In [9]:
try:
    view_4.view(2, 12)
except:
    print("view_4.view(2, 12) is not contigous")
    view_5 = view_4.view(2, 3, 4) # TODO why ok?
    
view_3.data_ptr(), view_5.data_ptr()

view_4.view(2, 12) is not contigous


(68811648, 68811648)

# reshpae (copy(robust, any tensor) or view )

In [10]:
reshape_0 = view_4.reshape(2, 12) # copy robust, view_4 is not contiguous
reshape_0[0][0] = 101

view_4, view_4.is_contiguous(), view_4.data_ptr(), \
'-----------------------------------------------', \
reshape_0, reshape_0.is_contiguous(), reshape_0.data_ptr()

(tensor([[100,   7,  13,  19],
         [  2,   8,  14,  20],
         [  3,   9,  15,  21],
         [  4,  10,  16,  22],
         [  5,  11,  17,  23],
         [  6,  12,  18,  24]]),
 False,
 68811648,
 '-----------------------------------------------',
 tensor([[101,   7,  13,  19,   2,   8,  14,  20,   3,   9,  15,  21],
         [  4,  10,  16,  22,   5,  11,  17,  23,   6,  12,  18,  24]]),
 True,
 68797696)

In [11]:
reshape_1 = view_3.reshape(6, 4) # view3 is contigous
reshape_1[0][0] = 102
view_3, view_3.is_contiguous(), view_3.data_ptr(), \
'-----------------------------------------------', \
reshape_1, reshape_1.is_contiguous(), reshape_1.data_ptr()

(tensor([[102,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12],
         [ 13,  14,  15,  16,  17,  18],
         [ 19,  20,  21,  22,  23,  24]]),
 True,
 68811648,
 '-----------------------------------------------',
 tensor([[102,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12],
         [ 13,  14,  15,  16],
         [ 17,  18,  19,  20],
         [ 21,  22,  23,  24]]),
 True,
 68811648)

In [12]:
reshape_2 = reshape_1.clone() # clone
reshape_2[0][0] = 103
reshape_1, reshape_1.data_ptr(), \
'-----------------------------', \
reshape_2, reshape_2.data_ptr()

(tensor([[102,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12],
         [ 13,  14,  15,  16],
         [ 17,  18,  19,  20],
         [ 21,  22,  23,  24]]),
 68811648,
 '-----------------------------',
 tensor([[103,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12],
         [ 13,  14,  15,  16],
         [ 17,  18,  19,  20],
         [ 21,  22,  23,  24]]),
 68782272)

In [13]:
reshape_3 = reshape_0.reshape(-1)
reshape_0, reshape_0.data_ptr(), \
'-----------------------------', \
reshape_3, reshape_3.data_ptr()

(tensor([[101,   7,  13,  19,   2,   8,  14,  20,   3,   9,  15,  21],
         [  4,  10,  16,  22,   5,  11,  17,  23,   6,  12,  18,  24]]),
 68797696,
 '-----------------------------',
 tensor([101,   7,  13,  19,   2,   8,  14,  20,   3,   9,  15,  21,   4,  10,
          16,  22,   5,  11,  17,  23,   6,  12,  18,  24]),
 68797696)

## transpose (only swap two dimension, memory not contiguous, view)

In [14]:
trans_0 = reshape_0.transpose(0, 1)
trans_1 = reshape_0.transpose(1, 0) # equal trans_0
reshape_0, reshape_0.shape, reshape_0.data_ptr(), reshape_0.is_contiguous(), \
'-------------------------------------------------------------------------', \
trans_0, trans_1, trans_0.shape, trans_0.data_ptr(), trans_0.is_contiguous()

(tensor([[101,   7,  13,  19,   2,   8,  14,  20,   3,   9,  15,  21],
         [  4,  10,  16,  22,   5,  11,  17,  23,   6,  12,  18,  24]]),
 torch.Size([2, 12]),
 68797696,
 True,
 '-------------------------------------------------------------------------',
 tensor([[101,   4],
         [  7,  10],
         [ 13,  16],
         [ 19,  22],
         [  2,   5],
         [  8,  11],
         [ 14,  17],
         [ 20,  23],
         [  3,   6],
         [  9,  12],
         [ 15,  18],
         [ 21,  24]]),
 tensor([[101,   4],
         [  7,  10],
         [ 13,  16],
         [ 19,  22],
         [  2,   5],
         [  8,  11],
         [ 14,  17],
         [ 20,  23],
         [  3,   6],
         [  9,  12],
         [ 15,  18],
         [ 21,  24]]),
 torch.Size([12, 2]),
 68797696,
 False)

In [15]:
trans_2 = view_0.transpose(1, 2)
view_0, view_0.shape, \
trans_2, trans_2.shape, \

(tensor([[[102,   2,   3,   4],
          [  5,   6,   7,   8],
          [  9,  10,  11,  12]],
 
         [[ 13,  14,  15,  16],
          [ 17,  18,  19,  20],
          [ 21,  22,  23,  24]]]),
 torch.Size([2, 3, 4]),
 tensor([[[102,   5,   9],
          [  2,   6,  10],
          [  3,   7,  11],
          [  4,   8,  12]],
 
         [[ 13,  17,  21],
          [ 14,  18,  22],
          [ 15,  19,  23],
          [ 16,  20,  24]]]),
 torch.Size([2, 4, 3]))

In [16]:
trans_0[0][0] = 111
reshape_0, reshape_0.is_contiguous(), \
'----------------------------------', \
trans_0, trans_0.is_contiguous()

(tensor([[111,   7,  13,  19,   2,   8,  14,  20,   3,   9,  15,  21],
         [  4,  10,  16,  22,   5,  11,  17,  23,   6,  12,  18,  24]]),
 True,
 '----------------------------------',
 tensor([[111,   4],
         [  7,  10],
         [ 13,  16],
         [ 19,  22],
         [  2,   5],
         [  8,  11],
         [ 14,  17],
         [ 20,  23],
         [  3,   6],
         [  9,  12],
         [ 15,  18],
         [ 21,  24]]),
 False)

In [17]:
trans_1 = trans_0.contiguous()
trans_1.data_ptr(), trans_0.data_ptr(), trans_1.is_contiguous()

(68750400, 68797696, True)

## permute (swap all the dimensions)

In [18]:
permute_0 = reshape_0.permute(1, 0) # same transpose
reshape_0, \
permute_0, trans_0

(tensor([[111,   7,  13,  19,   2,   8,  14,  20,   3,   9,  15,  21],
         [  4,  10,  16,  22,   5,  11,  17,  23,   6,  12,  18,  24]]),
 tensor([[111,   4],
         [  7,  10],
         [ 13,  16],
         [ 19,  22],
         [  2,   5],
         [  8,  11],
         [ 14,  17],
         [ 20,  23],
         [  3,   6],
         [  9,  12],
         [ 15,  18],
         [ 21,  24]]),
 tensor([[111,   4],
         [  7,  10],
         [ 13,  16],
         [ 19,  22],
         [  2,   5],
         [  8,  11],
         [ 14,  17],
         [ 20,  23],
         [  3,   6],
         [  9,  12],
         [ 15,  18],
         [ 21,  24]]))

In [19]:
permute_1 = view_0.permute(0, 2, 1) # same transpose(1, 2)
view_0, view_0.shape, \
permute_1, permute_1.shape

(tensor([[[102,   2,   3,   4],
          [  5,   6,   7,   8],
          [  9,  10,  11,  12]],
 
         [[ 13,  14,  15,  16],
          [ 17,  18,  19,  20],
          [ 21,  22,  23,  24]]]),
 torch.Size([2, 3, 4]),
 tensor([[[102,   5,   9],
          [  2,   6,  10],
          [  3,   7,  11],
          [  4,   8,  12]],
 
         [[ 13,  17,  21],
          [ 14,  18,  22],
          [ 15,  19,  23],
          [ 16,  20,  24]]]),
 torch.Size([2, 4, 3]))

# References

[Difference between view, reshape, transpose and permute in PyTorch][1]

[1]: (https://jdhao.github.io/2019/07/10/pytorch_view_reshape_transpose_permute/)