In [2]:
import torch

In [11]:
randi234 = torch.randint(low=1, high=24, size=(2,3,4))
randi234 

tensor([[[ 8, 16,  3,  5],
         [10, 12, 17, 23],
         [ 1,  3,  6,  7]],

        [[14, 11,  6, 18],
         [ 8, 16, 14, 15],
         [ 9, 13,  2,  5]]])

In [2]:
batch_pics = torch.rand(4, 3, 28, 28)
batch_pics.shape, batch_pics[0].shape, batch_pics[0, 0].shape, batch_pics[0, 0, 0]

(torch.Size([4, 3, 28, 28]),
 torch.Size([3, 28, 28]),
 torch.Size([28, 28]),
 tensor([0.6694, 0.8256, 0.7489, 0.1397, 0.7875, 0.7043, 0.1142, 0.3358, 0.5136,
         0.1293, 0.4332, 0.5507, 0.9628, 0.9811, 0.7141, 0.8963, 0.9787, 0.3335,
         0.6848, 0.6762, 0.0068, 0.0010, 0.3885, 0.0409, 0.3395, 0.9032, 0.9632,
         0.6162]))

# 取第一、第二张图片中的第一个通道

In [3]:
batch_pics[:2, 1, :, :].shape

torch.Size([2, 28, 28])

# 取第一、第二张图片中的第二个通道与第三个通道

In [4]:
batch_pics[:2, 1:, :, :].shape

torch.Size([2, 2, 28, 28])

# 取第一、第二张图片中的最后两个通道

In [5]:
batch_pics[:2, -2:, :, :].shape

torch.Size([2, 2, 28, 28])

# 第三、第四维度隔行采样

In [6]:
batch_pics[:, :, 0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

In [7]:
batch_pics[:, :, ::2, ::2].shape # 同上

torch.Size([4, 3, 14, 14])

## 索引任意多的维度

In [8]:
batch_pics[...].shape # == batch_pics

torch.Size([4, 3, 28, 28])

In [9]:
batch_pics[0, ...].shape # 第一张图片的所有维度

torch.Size([3, 28, 28])

In [10]:
batch_pics[:, 1, ...].shape # 所有图片第二通道的所有维度

torch.Size([4, 28, 28])

In [11]:
batch_pics[..., :2].shape # 所有图像所有通道所有行的第一、第二列

torch.Size([4, 3, 28, 2])

# mask索引 (结果被打平Flatten)

In [12]:
data = torch.randn(3, 4)
mask = data.ge(0.5)
data, mask, mask.shape

(tensor([[ 0.3337,  0.6265, -0.0600,  0.7349],
         [-2.5840,  0.1514,  0.6360,  1.0580],
         [ 0.8850,  0.3289, -1.0753, -0.3955]]),
 tensor([[False,  True, False,  True],
         [False, False,  True,  True],
         [ True, False, False, False]]),
 torch.Size([3, 4]))

In [13]:
result = torch.masked_select(data, mask)
result, result.shape # 被打平

(tensor([0.6265, 0.7349, 0.6360, 1.0580, 0.8850]), torch.Size([5]))

# take索引 (先打平在索引)

In [14]:
result = torch.take(data, torch.tensor([0, 1, -1]))
result, result.shape

(tensor([ 0.3337,  0.6265, -0.3955]), torch.Size([3]))

# 嵌套[ ]

In [13]:
data = randi234
data

tensor([[[ 8, 16,  3,  5],
         [10, 12, 17, 23],
         [ 1,  3,  6,  7]],

        [[14, 11,  6, 18],
         [ 8, 16, 14, 15],
         [ 9, 13,  2,  5]]])

In [17]:
data[:, 0], data[:, [0]] # 结果放入到[]

(tensor([[ 8, 16,  3,  5],
         [14, 11,  6, 18]]),
 tensor([[[ 8, 16,  3,  5]],
 
         [[14, 11,  6, 18]]]))

In [20]:
data[:, 0, 0], data[:, 0, [0]]

(tensor([ 8, 14]),
 tensor([[ 8],
         [14]]))

In [23]:
data[:, :, 0], data[:, :, [0]]

(tensor([[ 8, 10,  1],
         [14,  8,  9]]),
 tensor([[[ 8],
          [10],
          [ 1]],
 
         [[14],
          [ 8],
          [ 9]]]))

# References

[Pytorch Tensor的索引与切片][1]

[1]: https://blog.csdn.net/weicao1990/article/details/93599947