In [1]:
import torch

# torch.scatter_散射(torch.scatter)

scatter_(input, dim, index, src)将src中数据根据index中的索引按照dim的方向填进input中。


```py
y[index[i][j][k]][j][k] = x[i][j][k]  # if dim == 0
y[i][index[i][j][k]][k] = x[i][j][k]  # if dim == 1
y[i][j][index[i][j][k]] = x[i][j][k]  # if dim == 2
```


当dim=0时, index的值是y的dim=0的坐标

In [3]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,100],[11,12,13,14,15]], dtype=torch.float)
index = torch.tensor([[1,2,2,0,0],[2,0,0,1,2]])
y = torch.zeros(3, 5)

z = torch.scatter(y, dim=0, index=index, src=x)
y, x, index, z, z[index[0][0]][0], x[0][0], z[index[1][1]][1], x[1][1]

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[  1.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9., 100.],
         [ 11.,  12.,  13.,  14.,  15.]]),
 tensor([[1, 2, 2, 0, 0],
         [2, 0, 0, 1, 2]]),
 tensor([[  0.,   7.,   8.,   4.,   5.],
         [  1.,   0.,   0.,   9.,   0.],
         [  6.,   2.,   3.,   0., 100.]]),
 tensor(1.),
 tensor(1.),
 tensor(7.),
 tensor(7.))

In [4]:
print(x[:, 0, ...].shape)
print(y[:, 0, ...].shape) # 3 != 2
print(x.size(0), y.size(0))
try:
    index = torch.tensor([[0,1,2,0,0],[2,0,0,1,2]])
    z = torch.scatter(y, dim=1, index=index, value=1.2)
except:
    index = torch.tensor([[0,1,2,0,0],[2,0,0,1,2],[0,0,0,3,3]])
    z = torch.scatter(y, dim=1, index=index, value=1.2)
    
y, x, index, z, z.shape, z[0][index[0][0]]

torch.Size([3])
torch.Size([3])
3 3


(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[  1.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9., 100.],
         [ 11.,  12.,  13.,  14.,  15.]]),
 tensor([[0, 1, 2, 0, 0],
         [2, 0, 0, 1, 2],
         [0, 0, 0, 3, 3]]),
 tensor([[1.2000, 1.2000, 1.2000, 0.0000, 0.0000],
         [1.2000, 1.2000, 1.2000, 0.0000, 0.0000],
         [1.2000, 0.0000, 0.0000, 1.2000, 0.0000]]),
 torch.Size([3, 5]),
 tensor(1.2000))

In [5]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]], dtype=torch.float)
index = torch.tensor([[2,1,1,0,1],[2,0,0,1,2],[0,0,0,3,3]])

y = torch.zeros(3, 5)
z = torch.scatter(y, dim=1, index=index, src=x)

y, x, index, z

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.,  0.],
         [11., 12., 13., 14., 15.]]),
 tensor([[2, 1, 1, 0, 1],
         [2, 0, 0, 1, 2],
         [0, 0, 0, 3, 3]]),
 tensor([[ 4.,  5.,  1.,  0.,  0.],
         [ 8.,  9.,  0.,  0.,  0.],
         [13.,  0.,  0., 15.,  0.]]))

## one-hot



In [7]:
y = torch.zeros(5,5,dtype=torch.float32)
index = torch.tensor([[0,1,2,3,4]],dtype=torch.int64)
y, y.shape, index

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.Size([5, 5]),
 tensor([[0, 1, 2, 3, 4]]))

In [ ]:
z = torch.scatter(y, dim=0, index=index, value=1.0)
z

# torch.gather (收集)

根据index和dim将x中的数据挑选出来，放置到y中

```py
y[i][j][k] = x[index[i][j][k]][j][k]  # if dim == 0
y[i][j][k] = x[i][index[i][j][k]][k]  # if dim == 1
y[i][j][k] = x[i][j][index[i][j][k]]  # if dim == 2
```


```py
y[i][j] = x[index[i][j]][j]  # if dim == 0
y[i][j] = x[i][index[i][j]]  # if dim == 1
```

In [ ]:
x = torch.tensor([[1,2],[3,4]])
index = torch.tensor([[0,0],[1,0]])
y = torch.gather(input=x, dim=1, index=index)
x, index, y, y[0][1], x[0][index[0][1]]